# AppProject ArgoCD : `devhub`
#
# Un AppProject est votre brique de sécurité. Sans lui, n'importe quelle
# Application peut pointer vers n'importe quel repo et déployer dans
# n'importe quel namespace. C'est dangereux dans une plateforme partagée.
#
# Référence : https://argo-cd.readthedocs.io/en/stable/operator-manual/project-management/
#
# Étape 6 — à compléter.

apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: devhub
  namespace: argocd
spec:
  description: Plateforme DevHub Campus

  sourceRepos:
    - http://local-git-server.argocd.svc/git/devhub-campus.git

  destinations:
    - server: https://kubernetes.default.svc
      namespace: devhub-*
    - server: https://kubernetes.default.svc
      namespace: argocd

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"

  roles:
    - name: developer
      description: Rôle Developer pour DevHub Campus
      policies:
        - p, proj:devhub:developer, applications, get, devhub/*, allow
        - p, proj:devhub:developer, applications, sync, devhub/*, allow

  syncWindows:
    - kind: deny
      schedule: "0 18 * * *"
      duration: 14h
      applications: ["*"]
      manualSync: true

