# Surcharges pour l'environnement de développement (namespace devhub-dev).
# Ne mettez ICI que ce qui diffère de values.yaml.

image:
  repository: host.docker.internal:5001/annuaire
  tag: tp3-v5
  pullPolicy: Always

ingress:
  enabled: true
  host: annuaire.devhub.local

env:
  LOG_LEVEL: debug

monitoring:
  enabled: true

useDeployment: false
