# Surcharges pour l'environnement de développement (namespace devhub-dev).
# Ne mettez ICI que ce qui diffère de values.yaml.

image:
  repository: host.docker.internal:5001/annuaire
  tag: tp3-v7
  pullPolicy: Always

ingress:
  enabled: true
  host: annuaire.devhub.local

env:
  LOG_LEVEL: info
  FAIL_RATE: "0.1"

monitoring:
  enabled: true
  prometheusRule:
    enabled: true

useDeployment: false

notifications:
  enabled: true

rollout:
  canary:
    headerRouting:
      enabled: true
