# Application ArgoCD : kube-prometheus-stack
#
# Installe Prometheus, Alertmanager, Grafana, node-exporter et
# kube-state-metrics dans le namespace `monitoring` via le chart Helm
# de la communauté Prometheus.
#
# Étape 3 du poly.

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: devhub

  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: "65.5.0"
      helm:
        releaseName: kps
        valueFiles:
          - $values/platform-sre/values/kube-prometheus-stack-values.yaml
    - repoURL: https://github.com/benjpay-sys/tp-argocd.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
