apiVersion: v1
kind: Service
metadata:
  name: local-git-server
  namespace: argocd
spec:
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app: local-git-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-git-server
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: local-git-server
  template:
    metadata:
      labels:
        app: local-git-server
    spec:
      containers:
        - name: git-server
          image: aliolozy/tinygit:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: INIT_REPOS
              value: devhub-campus
