{
 "title": "DevHub Campus SRE - Services RED",
 "tags": [
  "devhub",
  "sre",
  "tp3"
 ],
 "templating": {
  "list": [
   { "name": "namespace", "query": "devhub-dev" },
   {
    "name": "service",
    "query": "label_values(http_requests_total{namespace=\"devhub-dev\"}, job)"
   }
  ]
 },
 "panels": [
  {
   "title": "Request Rate (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{namespace=\"\", job=\"\"}[5m])) by (route, status_class)",
     "legendFormat": "{{route}} {{status_class}}"
    }
   ]
  },
  {
   "title": "Error Rate (5xx ratio)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{namespace=\"\", job=\"\", status_class=\"5xx\"}[5m])) / sum(rate(http_requests_total{namespace=\"\", job=\"\"}[5m]))",
     "legendFormat": "error rate"
    }
   ]
  },
  {
   "title": "Latency p50 / p95 / p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_seconds_bucket{namespace=\"\", job=\"\"}[5m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{namespace=\"\", job=\"\"}[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{namespace=\"\", job=\"\"}[5m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Build Info (version actuelle)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (version, commit, language) (annuaire_build_info{namespace=\"\"}) or max by (version, commit, language) (planning_build_info{namespace=\"\"}) or max by (version, commit, language) (notif_build_info{namespace=\"\"})",
     "legendFormat": "{{version}} ({{language}}) @ {{commit}}"
    }
   ]
  }
 ]
}